FROM ubuntu:20.04

ARG TARGETARCH

# Systemd-based container setup
ENV container docker
RUN apt-get update -qq && apt-get install -y -q systemd systemd-sysv
#COPY integration_test/container.target /etc/systemd/system/container.target
#RUN ln -sf /etc/systemd/system/container.target /etc/systemd/system/default.target
RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
    /lib/systemd/system/systemd-update-utmp*
RUN systemctl set-default multi-user.target
#STOPSIGNAL SIGRTMIN+3
ENTRYPOINT ["/lib/systemd/systemd"]
CMD ["--log-level=info", "--unit=sysinit.target"]

ENV GOVERSION 1.17
ENV CODE_DIR /collector
ENV PATH $PATH:/usr/local/go/bin

# Packages required for both building and packaging
RUN apt-get update -qq && apt-get install -y -q build-essential git curl

# Golang
RUN curl -o go.tar.gz -sSL "https://golang.org/dl/go${GOVERSION}.linux-${TARGETARCH}.tar.gz"
RUN tar -C /usr/local -xzf go.tar.gz

# Build the collector
COPY . $CODE_DIR
WORKDIR $CODE_DIR
RUN make build_dist

# Make sure collector state can be saved
RUN mkdir /var/lib/pganalyze-collector/

RUN cp $CODE_DIR/pganalyze-collector /usr/bin/
RUN cp $CODE_DIR/pganalyze-collector-helper /usr/bin/
RUN cp $CODE_DIR/pganalyze-collector-setup /usr/bin/
RUN cp $CODE_DIR/contrib/pganalyze-collector.conf /etc/pganalyze-collector.conf

RUN sh $CODE_DIR/packages/src/deb-systemd/after-install.sh
