FROM phusion/baseimage:bionic-1.0.0

ENTRYPOINT [ "sleep", "infinity" ]

ENV GOVERSION 1.14.11
ENV CODE_DIR /collector
ENV PATH $PATH:/usr/local/go/bin

# Packages required for both building and packaging
RUN apt-get update -qq && apt-get install -y -q build-essential git curl

# Golang
RUN curl -o go.tar.gz -sSL "https://storage.googleapis.com/golang/go${GOVERSION}.linux-amd64.tar.gz"
RUN tar -C /usr/local -xzf go.tar.gz

# Build the collector
COPY . $CODE_DIR
WORKDIR $CODE_DIR
RUN make build_dist

# Make sure collector state can be saved
RUN mkdir /var/lib/pganalyze-collector/

RUN cp $CODE_DIR/pganalyze-collector /usr/bin/
RUN cp $CODE_DIR/pganalyze-collector-helper /usr/bin/
RUN cp $CODE_DIR/pganalyze-collector-setup /usr/bin/
RUN cp $CODE_DIR/contrib/pganalyze-collector.conf /etc/pganalyze-collector.conf

RUN sh $CODE_DIR/packages/src/deb-systemd/after-install.sh

# install postgres
RUN apt-get install --yes --quiet postgresql
ENV PATH $PATH:/usr/lib/postgresql/10/bin
RUN mkdir -p /var/run/postgresql/10-main.pg_stat_tmp
RUN chown --recursive postgres.postgres /var/run/postgresql/10-main.pg_stat_tmp
