{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pganalyze-collector.secretName" . }}
  labels:
    {{- include "pganalyze-collector.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret.values }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
