// Code generated by protoc-gen-go.
// source: snapshot.proto
// DO NOT EDIT!

/*
Package pganalyze_collector is a generated protocol buffer package.

It is generated from these files:
	snapshot.proto

It has these top-level messages:
	FullSnapshot
	NullString
	NullTimestamp
	RoleReference
	DatabaseReference
	RoleInformation
	DatabaseInformation
	PostgresVersion
	LogLine
	Setting
	Backend
	System
	RelationReference
	IndexReference
	FunctionReference
	QueryReference
	QueryInformation
	QueryStatistic
	QueryExplain
	RelationInformation
	RelationStatistic
	RelationEvent
	RelationBloatStatistic
	IndexInformation
	IndexStatistic
	IndexBloatStatistic
	FunctionInformation
	FunctionStatistic
*/
package pganalyze_collector

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type LogLine_SourceType int32

const (
	LogLine_PostgresSource  LogLine_SourceType = 0
	LogLine_AmazonRdsSource LogLine_SourceType = 1
)

var LogLine_SourceType_name = map[int32]string{
	0: "PostgresSource",
	1: "AmazonRdsSource",
}
var LogLine_SourceType_value = map[string]int32{
	"PostgresSource":  0,
	"AmazonRdsSource": 1,
}

func (x LogLine_SourceType) String() string {
	return proto.EnumName(LogLine_SourceType_name, int32(x))
}
func (LogLine_SourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type RelationEvent_EventType int32

const (
	RelationEvent_MANUAL_VACUUM  RelationEvent_EventType = 0
	RelationEvent_AUTO_VACUUM    RelationEvent_EventType = 1
	RelationEvent_MANUAL_ANALYZE RelationEvent_EventType = 2
	RelationEvent_AUTO_ANALYZE   RelationEvent_EventType = 3
)

var RelationEvent_EventType_name = map[int32]string{
	0: "MANUAL_VACUUM",
	1: "AUTO_VACUUM",
	2: "MANUAL_ANALYZE",
	3: "AUTO_ANALYZE",
}
var RelationEvent_EventType_value = map[string]int32{
	"MANUAL_VACUUM":  0,
	"AUTO_VACUUM":    1,
	"MANUAL_ANALYZE": 2,
	"AUTO_ANALYZE":   3,
}

func (x RelationEvent_EventType) String() string {
	return proto.EnumName(RelationEvent_EventType_name, int32(x))
}
func (RelationEvent_EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{21, 0} }

type FullSnapshot struct {
	// Basic information about this snapshot
	SnapshotVersionMajor  int32                      `protobuf:"varint,1,opt,name=snapshot_version_major,json=snapshotVersionMajor" json:"snapshot_version_major,omitempty"`
	SnapshotVersionMinor  int32                      `protobuf:"varint,2,opt,name=snapshot_version_minor,json=snapshotVersionMinor" json:"snapshot_version_minor,omitempty"`
	CollectorVersion      string                     `protobuf:"bytes,3,opt,name=collector_version,json=collectorVersion" json:"collector_version,omitempty"`
	SnapshotUuid          string                     `protobuf:"bytes,10,opt,name=snapshot_uuid,json=snapshotUuid" json:"snapshot_uuid,omitempty"`
	CollectedAt           *google_protobuf.Timestamp `protobuf:"bytes,11,opt,name=collected_at,json=collectedAt" json:"collected_at,omitempty"`
	CollectedIntervalSecs int32                      `protobuf:"varint,12,opt,name=collected_interval_secs,json=collectedIntervalSecs" json:"collected_interval_secs,omitempty"`
	// Per server (and hence snapshot)
	PostgresVersion      *PostgresVersion       `protobuf:"bytes,101,opt,name=postgres_version,json=postgresVersion" json:"postgres_version,omitempty"`
	RoleReferences       []*RoleReference       `protobuf:"bytes,102,rep,name=role_references,json=roleReferences" json:"role_references,omitempty"`
	DatabaseReferences   []*DatabaseReference   `protobuf:"bytes,103,rep,name=database_references,json=databaseReferences" json:"database_references,omitempty"`
	RoleInformations     []*RoleInformation     `protobuf:"bytes,110,rep,name=role_informations,json=roleInformations" json:"role_informations,omitempty"`
	DatabaseInformations []*DatabaseInformation `protobuf:"bytes,111,rep,name=database_informations,json=databaseInformations" json:"database_informations,omitempty"`
	Logs                 []*LogLine             `protobuf:"bytes,120,rep,name=logs" json:"logs,omitempty"`
	Backends             []*Backend             `protobuf:"bytes,121,rep,name=backends" json:"backends,omitempty"`
	Settings             []*Setting             `protobuf:"bytes,122,rep,name=settings" json:"settings,omitempty"`
	// Per database
	QueryReferences         []*QueryReference         `protobuf:"bytes,200,rep,name=query_references,json=queryReferences" json:"query_references,omitempty"`
	RelationReferences      []*RelationReference      `protobuf:"bytes,201,rep,name=relation_references,json=relationReferences" json:"relation_references,omitempty"`
	IndexReferences         []*IndexReference         `protobuf:"bytes,202,rep,name=index_references,json=indexReferences" json:"index_references,omitempty"`
	FunctionReferences      []*FunctionReference      `protobuf:"bytes,203,rep,name=function_references,json=functionReferences" json:"function_references,omitempty"`
	QueryInformations       []*QueryInformation       `protobuf:"bytes,210,rep,name=query_informations,json=queryInformations" json:"query_informations,omitempty"`
	QueryStatistics         []*QueryStatistic         `protobuf:"bytes,211,rep,name=query_statistics,json=queryStatistics" json:"query_statistics,omitempty"`
	QueryExplains           []*QueryExplain           `protobuf:"bytes,212,rep,name=query_explains,json=queryExplains" json:"query_explains,omitempty"`
	RelationInformations    []*RelationInformation    `protobuf:"bytes,220,rep,name=relation_informations,json=relationInformations" json:"relation_informations,omitempty"`
	RelationStatistics      []*RelationStatistic      `protobuf:"bytes,221,rep,name=relation_statistics,json=relationStatistics" json:"relation_statistics,omitempty"`
	RelationBloatStatistics []*RelationBloatStatistic `protobuf:"bytes,222,rep,name=relation_bloat_statistics,json=relationBloatStatistics" json:"relation_bloat_statistics,omitempty"`
	RelationEvents          []*RelationEvent          `protobuf:"bytes,223,rep,name=relation_events,json=relationEvents" json:"relation_events,omitempty"`
	IndexInformations       []*IndexInformation       `protobuf:"bytes,224,rep,name=index_informations,json=indexInformations" json:"index_informations,omitempty"`
	IndexStatistics         []*IndexStatistic         `protobuf:"bytes,225,rep,name=index_statistics,json=indexStatistics" json:"index_statistics,omitempty"`
	IndexBloatStatistics    []*IndexBloatStatistic    `protobuf:"bytes,226,rep,name=index_bloat_statistics,json=indexBloatStatistics" json:"index_bloat_statistics,omitempty"`
	FunctionInformations    []*FunctionInformation    `protobuf:"bytes,227,rep,name=function_informations,json=functionInformations" json:"function_informations,omitempty"`
	FunctionStatistics      []*FunctionStatistic      `protobuf:"bytes,228,rep,name=function_statistics,json=functionStatistics" json:"function_statistics,omitempty"`
}

func (m *FullSnapshot) Reset()                    { *m = FullSnapshot{} }
func (m *FullSnapshot) String() string            { return proto.CompactTextString(m) }
func (*FullSnapshot) ProtoMessage()               {}
func (*FullSnapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FullSnapshot) GetCollectedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CollectedAt
	}
	return nil
}

func (m *FullSnapshot) GetPostgresVersion() *PostgresVersion {
	if m != nil {
		return m.PostgresVersion
	}
	return nil
}

func (m *FullSnapshot) GetRoleReferences() []*RoleReference {
	if m != nil {
		return m.RoleReferences
	}
	return nil
}

func (m *FullSnapshot) GetDatabaseReferences() []*DatabaseReference {
	if m != nil {
		return m.DatabaseReferences
	}
	return nil
}

func (m *FullSnapshot) GetRoleInformations() []*RoleInformation {
	if m != nil {
		return m.RoleInformations
	}
	return nil
}

func (m *FullSnapshot) GetDatabaseInformations() []*DatabaseInformation {
	if m != nil {
		return m.DatabaseInformations
	}
	return nil
}

func (m *FullSnapshot) GetLogs() []*LogLine {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *FullSnapshot) GetBackends() []*Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

func (m *FullSnapshot) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *FullSnapshot) GetQueryReferences() []*QueryReference {
	if m != nil {
		return m.QueryReferences
	}
	return nil
}

func (m *FullSnapshot) GetRelationReferences() []*RelationReference {
	if m != nil {
		return m.RelationReferences
	}
	return nil
}

func (m *FullSnapshot) GetIndexReferences() []*IndexReference {
	if m != nil {
		return m.IndexReferences
	}
	return nil
}

func (m *FullSnapshot) GetFunctionReferences() []*FunctionReference {
	if m != nil {
		return m.FunctionReferences
	}
	return nil
}

func (m *FullSnapshot) GetQueryInformations() []*QueryInformation {
	if m != nil {
		return m.QueryInformations
	}
	return nil
}

func (m *FullSnapshot) GetQueryStatistics() []*QueryStatistic {
	if m != nil {
		return m.QueryStatistics
	}
	return nil
}

func (m *FullSnapshot) GetQueryExplains() []*QueryExplain {
	if m != nil {
		return m.QueryExplains
	}
	return nil
}

func (m *FullSnapshot) GetRelationInformations() []*RelationInformation {
	if m != nil {
		return m.RelationInformations
	}
	return nil
}

func (m *FullSnapshot) GetRelationStatistics() []*RelationStatistic {
	if m != nil {
		return m.RelationStatistics
	}
	return nil
}

func (m *FullSnapshot) GetRelationBloatStatistics() []*RelationBloatStatistic {
	if m != nil {
		return m.RelationBloatStatistics
	}
	return nil
}

func (m *FullSnapshot) GetRelationEvents() []*RelationEvent {
	if m != nil {
		return m.RelationEvents
	}
	return nil
}

func (m *FullSnapshot) GetIndexInformations() []*IndexInformation {
	if m != nil {
		return m.IndexInformations
	}
	return nil
}

func (m *FullSnapshot) GetIndexStatistics() []*IndexStatistic {
	if m != nil {
		return m.IndexStatistics
	}
	return nil
}

func (m *FullSnapshot) GetIndexBloatStatistics() []*IndexBloatStatistic {
	if m != nil {
		return m.IndexBloatStatistics
	}
	return nil
}

func (m *FullSnapshot) GetFunctionInformations() []*FunctionInformation {
	if m != nil {
		return m.FunctionInformations
	}
	return nil
}

func (m *FullSnapshot) GetFunctionStatistics() []*FunctionStatistic {
	if m != nil {
		return m.FunctionStatistics
	}
	return nil
}

type NullString struct {
	Valid bool   `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *NullString) Reset()                    { *m = NullString{} }
func (m *NullString) String() string            { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()               {}
func (*NullString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NullTimestamp struct {
	Valid bool                       `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	Value *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *NullTimestamp) Reset()                    { *m = NullTimestamp{} }
func (m *NullTimestamp) String() string            { return proto.CompactTextString(m) }
func (*NullTimestamp) ProtoMessage()               {}
func (*NullTimestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NullTimestamp) GetValue() *google_protobuf.Timestamp {
	if m != nil {
		return m.Value
	}
	return nil
}

type RoleReference struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *RoleReference) Reset()                    { *m = RoleReference{} }
func (m *RoleReference) String() string            { return proto.CompactTextString(m) }
func (*RoleReference) ProtoMessage()               {}
func (*RoleReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DatabaseReference struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DatabaseReference) Reset()                    { *m = DatabaseReference{} }
func (m *DatabaseReference) String() string            { return proto.CompactTextString(m) }
func (*DatabaseReference) ProtoMessage()               {}
func (*DatabaseReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type RoleInformation struct {
	RoleIdx            int32          `protobuf:"varint,1,opt,name=role_idx,json=roleIdx" json:"role_idx,omitempty"`
	Inherit            bool           `protobuf:"varint,2,opt,name=inherit" json:"inherit,omitempty"`
	Login              bool           `protobuf:"varint,3,opt,name=login" json:"login,omitempty"`
	CreateDb           bool           `protobuf:"varint,4,opt,name=create_db,json=createDb" json:"create_db,omitempty"`
	CreateRole         bool           `protobuf:"varint,5,opt,name=create_role,json=createRole" json:"create_role,omitempty"`
	SuperUser          bool           `protobuf:"varint,6,opt,name=super_user,json=superUser" json:"super_user,omitempty"`
	Replication        bool           `protobuf:"varint,7,opt,name=replication" json:"replication,omitempty"`
	BypassRls          bool           `protobuf:"varint,8,opt,name=bypass_rls,json=bypassRls" json:"bypass_rls,omitempty"`
	ConnectionLimit    int32          `protobuf:"varint,9,opt,name=connection_limit,json=connectionLimit" json:"connection_limit,omitempty"`
	PasswordValidUntil *NullTimestamp `protobuf:"bytes,10,opt,name=password_valid_until,json=passwordValidUntil" json:"password_valid_until,omitempty"`
	Config             []string       `protobuf:"bytes,11,rep,name=config" json:"config,omitempty"`
	MemberOf           []int32        `protobuf:"varint,12,rep,name=member_of,json=memberOf" json:"member_of,omitempty"`
}

func (m *RoleInformation) Reset()                    { *m = RoleInformation{} }
func (m *RoleInformation) String() string            { return proto.CompactTextString(m) }
func (*RoleInformation) ProtoMessage()               {}
func (*RoleInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RoleInformation) GetPasswordValidUntil() *NullTimestamp {
	if m != nil {
		return m.PasswordValidUntil
	}
	return nil
}

type DatabaseInformation struct {
	DatabaseIdx      int32  `protobuf:"varint,1,opt,name=database_idx,json=databaseIdx" json:"database_idx,omitempty"`
	OwnerRoleIdx     int32  `protobuf:"varint,2,opt,name=owner_role_idx,json=ownerRoleIdx" json:"owner_role_idx,omitempty"`
	Encoding         string `protobuf:"bytes,3,opt,name=encoding" json:"encoding,omitempty"`
	Collate          string `protobuf:"bytes,4,opt,name=collate" json:"collate,omitempty"`
	CType            string `protobuf:"bytes,5,opt,name=c_type,json=cType" json:"c_type,omitempty"`
	IsTemplate       bool   `protobuf:"varint,6,opt,name=is_template,json=isTemplate" json:"is_template,omitempty"`
	AllowConnections bool   `protobuf:"varint,7,opt,name=allow_connections,json=allowConnections" json:"allow_connections,omitempty"`
	ConnectionLimit  int32  `protobuf:"varint,8,opt,name=connection_limit,json=connectionLimit" json:"connection_limit,omitempty"`
	// All transaction IDs before this one have been replaced with a permanent ("frozen") transaction ID in this database.
	// This is used to track whether the database needs to be vacuumed in order to prevent transaction ID wraparound or to
	// allow pg_clog to be shrunk. It is the minimum of the per-table pg_class.relfrozenxid values.
	FrozenXid uint32 `protobuf:"varint,9,opt,name=frozen_xid,json=frozenXid" json:"frozen_xid,omitempty"`
	// All multixact IDs before this one have been replaced with a transaction ID in this database.
	// This is used to track whether the database needs to be vacuumed in order to prevent multixact ID wraparound or to
	// allow pg_multixact to be shrunk. It is the minimum of the per-table pg_class.relminmxid values.
	MinimumMultixactXid uint32 `protobuf:"varint,10,opt,name=minimum_multixact_xid,json=minimumMultixactXid" json:"minimum_multixact_xid,omitempty"`
}

func (m *DatabaseInformation) Reset()                    { *m = DatabaseInformation{} }
func (m *DatabaseInformation) String() string            { return proto.CompactTextString(m) }
func (*DatabaseInformation) ProtoMessage()               {}
func (*DatabaseInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type PostgresVersion struct {
	Full    string `protobuf:"bytes,1,opt,name=full" json:"full,omitempty"`
	Short   string `protobuf:"bytes,2,opt,name=short" json:"short,omitempty"`
	Numeric int64  `protobuf:"varint,3,opt,name=numeric" json:"numeric,omitempty"`
}

func (m *PostgresVersion) Reset()                    { *m = PostgresVersion{} }
func (m *PostgresVersion) String() string            { return proto.CompactTextString(m) }
func (*PostgresVersion) ProtoMessage()               {}
func (*PostgresVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type LogLine struct {
	OccurredAt      int64              `protobuf:"varint,1,opt,name=occurred_at,json=occurredAt" json:"occurred_at,omitempty"`
	Source          LogLine_SourceType `protobuf:"varint,2,opt,name=source,enum=pganalyze.collector.LogLine_SourceType" json:"source,omitempty"`
	ClientIp        *NullString        `protobuf:"bytes,3,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	LogLevel        string             `protobuf:"bytes,4,opt,name=log_level,json=logLevel" json:"log_level,omitempty"`
	BackendPid      int32              `protobuf:"varint,5,opt,name=backend_pid,json=backendPid" json:"backend_pid,omitempty"`
	Content         string             `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	AdditionalLines []*LogLine         `protobuf:"bytes,7,rep,name=additional_lines,json=additionalLines" json:"additional_lines,omitempty"`
}

func (m *LogLine) Reset()                    { *m = LogLine{} }
func (m *LogLine) String() string            { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()               {}
func (*LogLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LogLine) GetClientIp() *NullString {
	if m != nil {
		return m.ClientIp
	}
	return nil
}

func (m *LogLine) GetAdditionalLines() []*LogLine {
	if m != nil {
		return m.AdditionalLines
	}
	return nil
}

type Setting struct {
	Name         string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CurrentValue string      `protobuf:"bytes,2,opt,name=current_value,json=currentValue" json:"current_value,omitempty"`
	Unit         *NullString `protobuf:"bytes,3,opt,name=unit" json:"unit,omitempty"`
	BootValue    *NullString `protobuf:"bytes,4,opt,name=boot_value,json=bootValue" json:"boot_value,omitempty"`
	ResetValue   *NullString `protobuf:"bytes,5,opt,name=reset_value,json=resetValue" json:"reset_value,omitempty"`
	Source       *NullString `protobuf:"bytes,6,opt,name=source" json:"source,omitempty"`
	SourceFile   *NullString `protobuf:"bytes,7,opt,name=source_file,json=sourceFile" json:"source_file,omitempty"`
	SourceLine   *NullString `protobuf:"bytes,8,opt,name=source_line,json=sourceLine" json:"source_line,omitempty"`
}

func (m *Setting) Reset()                    { *m = Setting{} }
func (m *Setting) String() string            { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()               {}
func (*Setting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Setting) GetUnit() *NullString {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *Setting) GetBootValue() *NullString {
	if m != nil {
		return m.BootValue
	}
	return nil
}

func (m *Setting) GetResetValue() *NullString {
	if m != nil {
		return m.ResetValue
	}
	return nil
}

func (m *Setting) GetSource() *NullString {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Setting) GetSourceFile() *NullString {
	if m != nil {
		return m.SourceFile
	}
	return nil
}

func (m *Setting) GetSourceLine() *NullString {
	if m != nil {
		return m.SourceLine
	}
	return nil
}

type Backend struct {
	Pid             int64                      `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Username        string                     `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	ApplicationName string                     `protobuf:"bytes,3,opt,name=application_name,json=applicationName" json:"application_name,omitempty"`
	ClientAddr      string                     `protobuf:"bytes,4,opt,name=client_addr,json=clientAddr" json:"client_addr,omitempty"`
	BackendStart    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=backend_start,json=backendStart" json:"backend_start,omitempty"`
	XactStart       *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=xact_start,json=xactStart" json:"xact_start,omitempty"`
	QueryStart      *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=query_start,json=queryStart" json:"query_start,omitempty"`
	StateChange     *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=state_change,json=stateChange" json:"state_change,omitempty"`
	Waiting         bool                       `protobuf:"varint,9,opt,name=waiting" json:"waiting,omitempty"`
	State           string                     `protobuf:"bytes,10,opt,name=state" json:"state,omitempty"`
	NormalizedQuery string                     `protobuf:"bytes,11,opt,name=normalized_query,json=normalizedQuery" json:"normalized_query,omitempty"`
}

func (m *Backend) Reset()                    { *m = Backend{} }
func (m *Backend) String() string            { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()               {}
func (*Backend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Backend) GetBackendStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.BackendStart
	}
	return nil
}

func (m *Backend) GetXactStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.XactStart
	}
	return nil
}

func (m *Backend) GetQueryStart() *google_protobuf.Timestamp {
	if m != nil {
		return m.QueryStart
	}
	return nil
}

func (m *Backend) GetStateChange() *google_protobuf.Timestamp {
	if m != nil {
		return m.StateChange
	}
	return nil
}

type System struct {
}

func (m *System) Reset()                    { *m = System{} }
func (m *System) String() string            { return proto.CompactTextString(m) }
func (*System) ProtoMessage()               {}
func (*System) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type RelationReference struct {
	DatabaseIdx  int32  `protobuf:"varint,1,opt,name=database_idx,json=databaseIdx" json:"database_idx,omitempty"`
	SchemaName   string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName" json:"schema_name,omitempty"`
	RelationName string `protobuf:"bytes,3,opt,name=relation_name,json=relationName" json:"relation_name,omitempty"`
}

func (m *RelationReference) Reset()                    { *m = RelationReference{} }
func (m *RelationReference) String() string            { return proto.CompactTextString(m) }
func (*RelationReference) ProtoMessage()               {}
func (*RelationReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type IndexReference struct {
	DatabaseIdx int32  `protobuf:"varint,1,opt,name=database_idx,json=databaseIdx" json:"database_idx,omitempty"`
	SchemaName  string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName" json:"schema_name,omitempty"`
	IndexName   string `protobuf:"bytes,3,opt,name=index_name,json=indexName" json:"index_name,omitempty"`
}

func (m *IndexReference) Reset()                    { *m = IndexReference{} }
func (m *IndexReference) String() string            { return proto.CompactTextString(m) }
func (*IndexReference) ProtoMessage()               {}
func (*IndexReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type FunctionReference struct {
	DatabaseIdx  int32  `protobuf:"varint,1,opt,name=database_idx,json=databaseIdx" json:"database_idx,omitempty"`
	SchemaName   string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName" json:"schema_name,omitempty"`
	FunctionName string `protobuf:"bytes,3,opt,name=function_name,json=functionName" json:"function_name,omitempty"`
	Arguments    string `protobuf:"bytes,4,opt,name=arguments" json:"arguments,omitempty"`
}

func (m *FunctionReference) Reset()                    { *m = FunctionReference{} }
func (m *FunctionReference) String() string            { return proto.CompactTextString(m) }
func (*FunctionReference) ProtoMessage()               {}
func (*FunctionReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type QueryReference struct {
	DatabaseIdx int32  `protobuf:"varint,1,opt,name=database_idx,json=databaseIdx" json:"database_idx,omitempty"`
	RoleIdx     int32  `protobuf:"varint,2,opt,name=role_idx,json=roleIdx" json:"role_idx,omitempty"`
	Fingerprint []byte `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
}

func (m *QueryReference) Reset()                    { *m = QueryReference{} }
func (m *QueryReference) String() string            { return proto.CompactTextString(m) }
func (*QueryReference) ProtoMessage()               {}
func (*QueryReference) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type QueryInformation struct {
	QueryIdx        int32   `protobuf:"varint,1,opt,name=query_idx,json=queryIdx" json:"query_idx,omitempty"`
	NormalizedQuery string  `protobuf:"bytes,2,opt,name=normalized_query,json=normalizedQuery" json:"normalized_query,omitempty"`
	QueryIds        []int64 `protobuf:"varint,3,rep,name=query_ids,json=queryIds" json:"query_ids,omitempty"`
}

func (m *QueryInformation) Reset()                    { *m = QueryInformation{} }
func (m *QueryInformation) String() string            { return proto.CompactTextString(m) }
func (*QueryInformation) ProtoMessage()               {}
func (*QueryInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type QueryStatistic struct {
	QueryIdx          int32   `protobuf:"varint,1,opt,name=query_idx,json=queryIdx" json:"query_idx,omitempty"`
	Calls             int64   `protobuf:"varint,2,opt,name=calls" json:"calls,omitempty"`
	TotalTime         float64 `protobuf:"fixed64,3,opt,name=total_time,json=totalTime" json:"total_time,omitempty"`
	Rows              int64   `protobuf:"varint,4,opt,name=rows" json:"rows,omitempty"`
	SharedBlksHit     int64   `protobuf:"varint,5,opt,name=shared_blks_hit,json=sharedBlksHit" json:"shared_blks_hit,omitempty"`
	SharedBlksRead    int64   `protobuf:"varint,6,opt,name=shared_blks_read,json=sharedBlksRead" json:"shared_blks_read,omitempty"`
	SharedBlksDirtied int64   `protobuf:"varint,7,opt,name=shared_blks_dirtied,json=sharedBlksDirtied" json:"shared_blks_dirtied,omitempty"`
	SharedBlksWritten int64   `protobuf:"varint,8,opt,name=shared_blks_written,json=sharedBlksWritten" json:"shared_blks_written,omitempty"`
	LocalBlksHit      int64   `protobuf:"varint,9,opt,name=local_blks_hit,json=localBlksHit" json:"local_blks_hit,omitempty"`
	LocalBlksRead     int64   `protobuf:"varint,10,opt,name=local_blks_read,json=localBlksRead" json:"local_blks_read,omitempty"`
	LocalBlksDirtied  int64   `protobuf:"varint,11,opt,name=local_blks_dirtied,json=localBlksDirtied" json:"local_blks_dirtied,omitempty"`
	LocalBlksWritten  int64   `protobuf:"varint,12,opt,name=local_blks_written,json=localBlksWritten" json:"local_blks_written,omitempty"`
	TempBlksRead      int64   `protobuf:"varint,13,opt,name=temp_blks_read,json=tempBlksRead" json:"temp_blks_read,omitempty"`
	TempBlksWritten   int64   `protobuf:"varint,14,opt,name=temp_blks_written,json=tempBlksWritten" json:"temp_blks_written,omitempty"`
	BlkReadTime       float64 `protobuf:"fixed64,15,opt,name=blk_read_time,json=blkReadTime" json:"blk_read_time,omitempty"`
	BlkWriteTime      float64 `protobuf:"fixed64,16,opt,name=blk_write_time,json=blkWriteTime" json:"blk_write_time,omitempty"`
}

func (m *QueryStatistic) Reset()                    { *m = QueryStatistic{} }
func (m *QueryStatistic) String() string            { return proto.CompactTextString(m) }
func (*QueryStatistic) ProtoMessage()               {}
func (*QueryStatistic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type QueryExplain struct {
	QueryIdx      int32   `protobuf:"varint,1,opt,name=query_idx,json=queryIdx" json:"query_idx,omitempty"`
	OccurredAt    int64   `protobuf:"varint,4,opt,name=occurred_at,json=occurredAt" json:"occurred_at,omitempty"`
	Runtime       float64 `protobuf:"fixed64,5,opt,name=runtime" json:"runtime,omitempty"`
	ExplainOutput string  `protobuf:"bytes,6,opt,name=explain_output,json=explainOutput" json:"explain_output,omitempty"`
	ExplainError  string  `protobuf:"bytes,7,opt,name=explain_error,json=explainError" json:"explain_error,omitempty"`
}

func (m *QueryExplain) Reset()                    { *m = QueryExplain{} }
func (m *QueryExplain) String() string            { return proto.CompactTextString(m) }
func (*QueryExplain) ProtoMessage()               {}
func (*QueryExplain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type RelationInformation struct {
	RelationIdx            int32                             `protobuf:"varint,1,opt,name=relation_idx,json=relationIdx" json:"relation_idx,omitempty"`
	RelationType           string                            `protobuf:"bytes,2,opt,name=relation_type,json=relationType" json:"relation_type,omitempty"`
	ViewDefinition         *NullString                       `protobuf:"bytes,3,opt,name=view_definition,json=viewDefinition" json:"view_definition,omitempty"`
	Columns                []*RelationInformation_Column     `protobuf:"bytes,4,rep,name=columns" json:"columns,omitempty"`
	Constraints            []*RelationInformation_Constraint `protobuf:"bytes,5,rep,name=constraints" json:"constraints,omitempty"`
	PersistenceType        string                            `protobuf:"bytes,6,opt,name=persistence_type,json=persistenceType" json:"persistence_type,omitempty"`
	Fillfactor             int32                             `protobuf:"varint,7,opt,name=fillfactor" json:"fillfactor,omitempty"`
	HasOids                bool                              `protobuf:"varint,8,opt,name=has_oids,json=hasOids" json:"has_oids,omitempty"`
	HasInheritanceChildren bool                              `protobuf:"varint,9,opt,name=has_inheritance_children,json=hasInheritanceChildren" json:"has_inheritance_children,omitempty"`
	HasToast               bool                              `protobuf:"varint,10,opt,name=has_toast,json=hasToast" json:"has_toast,omitempty"`
	FrozenXid              uint32                            `protobuf:"varint,11,opt,name=frozen_xid,json=frozenXid" json:"frozen_xid,omitempty"`
	MinimumMultixactXid    uint32                            `protobuf:"varint,12,opt,name=minimum_multixact_xid,json=minimumMultixactXid" json:"minimum_multixact_xid,omitempty"`
}

func (m *RelationInformation) Reset()                    { *m = RelationInformation{} }
func (m *RelationInformation) String() string            { return proto.CompactTextString(m) }
func (*RelationInformation) ProtoMessage()               {}
func (*RelationInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RelationInformation) GetViewDefinition() *NullString {
	if m != nil {
		return m.ViewDefinition
	}
	return nil
}

func (m *RelationInformation) GetColumns() []*RelationInformation_Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *RelationInformation) GetConstraints() []*RelationInformation_Constraint {
	if m != nil {
		return m.Constraints
	}
	return nil
}

type RelationInformation_Column struct {
	Name         string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	DataType     string      `protobuf:"bytes,3,opt,name=data_type,json=dataType" json:"data_type,omitempty"`
	DefaultValue *NullString `protobuf:"bytes,4,opt,name=default_value,json=defaultValue" json:"default_value,omitempty"`
	NotNull      bool        `protobuf:"varint,5,opt,name=not_null,json=notNull" json:"not_null,omitempty"`
	Position     int32       `protobuf:"varint,6,opt,name=position" json:"position,omitempty"`
}

func (m *RelationInformation_Column) Reset()                    { *m = RelationInformation_Column{} }
func (m *RelationInformation_Column) String() string            { return proto.CompactTextString(m) }
func (*RelationInformation_Column) ProtoMessage()               {}
func (*RelationInformation_Column) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19, 0} }

func (m *RelationInformation_Column) GetDefaultValue() *NullString {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

type RelationInformation_Constraint struct {
	ForeignRelationIdx int32   `protobuf:"varint,1,opt,name=foreign_relation_idx,json=foreignRelationIdx" json:"foreign_relation_idx,omitempty"`
	Name               string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type               string  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	ConstraintDef      string  `protobuf:"bytes,4,opt,name=constraint_def,json=constraintDef" json:"constraint_def,omitempty"`
	Columns            []int32 `protobuf:"varint,5,rep,name=columns" json:"columns,omitempty"`
	ForeignColumns     []int32 `protobuf:"varint,6,rep,name=foreign_columns,json=foreignColumns" json:"foreign_columns,omitempty"`
	ForeignUpdateType  string  `protobuf:"bytes,7,opt,name=foreign_update_type,json=foreignUpdateType" json:"foreign_update_type,omitempty"`
	ForeignDeleteType  string  `protobuf:"bytes,8,opt,name=foreign_delete_type,json=foreignDeleteType" json:"foreign_delete_type,omitempty"`
	ForeignMatchType   string  `protobuf:"bytes,9,opt,name=foreign_match_type,json=foreignMatchType" json:"foreign_match_type,omitempty"`
}

func (m *RelationInformation_Constraint) Reset()         { *m = RelationInformation_Constraint{} }
func (m *RelationInformation_Constraint) String() string { return proto.CompactTextString(m) }
func (*RelationInformation_Constraint) ProtoMessage()    {}
func (*RelationInformation_Constraint) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19, 1}
}

type RelationStatistic struct {
	RelationIdx      int32 `protobuf:"varint,1,opt,name=relation_idx,json=relationIdx" json:"relation_idx,omitempty"`
	SizeBytes        int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes" json:"size_bytes,omitempty"`
	SeqScan          int64 `protobuf:"varint,3,opt,name=seq_scan,json=seqScan" json:"seq_scan,omitempty"`
	SeqTupRead       int64 `protobuf:"varint,4,opt,name=seq_tup_read,json=seqTupRead" json:"seq_tup_read,omitempty"`
	IdxScan          int64 `protobuf:"varint,5,opt,name=idx_scan,json=idxScan" json:"idx_scan,omitempty"`
	IdxTupFetch      int64 `protobuf:"varint,6,opt,name=idx_tup_fetch,json=idxTupFetch" json:"idx_tup_fetch,omitempty"`
	NTupIns          int64 `protobuf:"varint,7,opt,name=n_tup_ins,json=nTupIns" json:"n_tup_ins,omitempty"`
	NTupUpd          int64 `protobuf:"varint,8,opt,name=n_tup_upd,json=nTupUpd" json:"n_tup_upd,omitempty"`
	NTupDel          int64 `protobuf:"varint,9,opt,name=n_tup_del,json=nTupDel" json:"n_tup_del,omitempty"`
	NTupHotUpd       int64 `protobuf:"varint,10,opt,name=n_tup_hot_upd,json=nTupHotUpd" json:"n_tup_hot_upd,omitempty"`
	NLiveTup         int64 `protobuf:"varint,11,opt,name=n_live_tup,json=nLiveTup" json:"n_live_tup,omitempty"`
	NDeadTup         int64 `protobuf:"varint,12,opt,name=n_dead_tup,json=nDeadTup" json:"n_dead_tup,omitempty"`
	NModSinceAnalyze int64 `protobuf:"varint,13,opt,name=n_mod_since_analyze,json=nModSinceAnalyze" json:"n_mod_since_analyze,omitempty"`
	HeapBlksRead     int64 `protobuf:"varint,18,opt,name=heap_blks_read,json=heapBlksRead" json:"heap_blks_read,omitempty"`
	HeapBlksHit      int64 `protobuf:"varint,19,opt,name=heap_blks_hit,json=heapBlksHit" json:"heap_blks_hit,omitempty"`
	IdxBlksRead      int64 `protobuf:"varint,20,opt,name=idx_blks_read,json=idxBlksRead" json:"idx_blks_read,omitempty"`
	IdxBlksHit       int64 `protobuf:"varint,21,opt,name=idx_blks_hit,json=idxBlksHit" json:"idx_blks_hit,omitempty"`
	ToastBlksRead    int64 `protobuf:"varint,22,opt,name=toast_blks_read,json=toastBlksRead" json:"toast_blks_read,omitempty"`
	ToastBlksHit     int64 `protobuf:"varint,23,opt,name=toast_blks_hit,json=toastBlksHit" json:"toast_blks_hit,omitempty"`
	TidxBlksRead     int64 `protobuf:"varint,24,opt,name=tidx_blks_read,json=tidxBlksRead" json:"tidx_blks_read,omitempty"`
	TidxBlksHit      int64 `protobuf:"varint,25,opt,name=tidx_blks_hit,json=tidxBlksHit" json:"tidx_blks_hit,omitempty"`
}

func (m *RelationStatistic) Reset()                    { *m = RelationStatistic{} }
func (m *RelationStatistic) String() string            { return proto.CompactTextString(m) }
func (*RelationStatistic) ProtoMessage()               {}
func (*RelationStatistic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type RelationEvent struct {
	RelationIdx           int32                      `protobuf:"varint,1,opt,name=relation_idx,json=relationIdx" json:"relation_idx,omitempty"`
	Type                  RelationEvent_EventType    `protobuf:"varint,2,opt,name=type,enum=pganalyze.collector.RelationEvent_EventType" json:"type,omitempty"`
	OccurredAt            *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt" json:"occurred_at,omitempty"`
	ApproximateOccurredAt bool                       `protobuf:"varint,4,opt,name=approximate_occurred_at,json=approximateOccurredAt" json:"approximate_occurred_at,omitempty"`
}

func (m *RelationEvent) Reset()                    { *m = RelationEvent{} }
func (m *RelationEvent) String() string            { return proto.CompactTextString(m) }
func (*RelationEvent) ProtoMessage()               {}
func (*RelationEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RelationEvent) GetOccurredAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.OccurredAt
	}
	return nil
}

type RelationBloatStatistic struct {
	RelationIdx int32 `protobuf:"varint,1,opt,name=relation_idx,json=relationIdx" json:"relation_idx,omitempty"`
	WastedBytes int64 `protobuf:"varint,2,opt,name=wasted_bytes,json=wastedBytes" json:"wasted_bytes,omitempty"`
	SizeBytes   int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes" json:"size_bytes,omitempty"`
}

func (m *RelationBloatStatistic) Reset()                    { *m = RelationBloatStatistic{} }
func (m *RelationBloatStatistic) String() string            { return proto.CompactTextString(m) }
func (*RelationBloatStatistic) ProtoMessage()               {}
func (*RelationBloatStatistic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type IndexInformation struct {
	IndexIdx      int32       `protobuf:"varint,1,opt,name=index_idx,json=indexIdx" json:"index_idx,omitempty"`
	RelationIdx   int32       `protobuf:"varint,2,opt,name=relation_idx,json=relationIdx" json:"relation_idx,omitempty"`
	Columns       []int32     `protobuf:"varint,3,rep,name=columns" json:"columns,omitempty"`
	IndexDef      string      `protobuf:"bytes,4,opt,name=index_def,json=indexDef" json:"index_def,omitempty"`
	ConstraintDef *NullString `protobuf:"bytes,5,opt,name=constraint_def,json=constraintDef" json:"constraint_def,omitempty"`
	IsPrimary     bool        `protobuf:"varint,6,opt,name=is_primary,json=isPrimary" json:"is_primary,omitempty"`
	IsUnique      bool        `protobuf:"varint,7,opt,name=is_unique,json=isUnique" json:"is_unique,omitempty"`
	IsValid       bool        `protobuf:"varint,8,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
	Fillfactor    int32       `protobuf:"varint,9,opt,name=fillfactor" json:"fillfactor,omitempty"`
}

func (m *IndexInformation) Reset()                    { *m = IndexInformation{} }
func (m *IndexInformation) String() string            { return proto.CompactTextString(m) }
func (*IndexInformation) ProtoMessage()               {}
func (*IndexInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *IndexInformation) GetConstraintDef() *NullString {
	if m != nil {
		return m.ConstraintDef
	}
	return nil
}

type IndexStatistic struct {
	IndexIdx    int32 `protobuf:"varint,1,opt,name=index_idx,json=indexIdx" json:"index_idx,omitempty"`
	SizeBytes   int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes" json:"size_bytes,omitempty"`
	IdxScan     int64 `protobuf:"varint,3,opt,name=idx_scan,json=idxScan" json:"idx_scan,omitempty"`
	IdxTupRead  int64 `protobuf:"varint,4,opt,name=idx_tup_read,json=idxTupRead" json:"idx_tup_read,omitempty"`
	IdxTupFetch int64 `protobuf:"varint,6,opt,name=idx_tup_fetch,json=idxTupFetch" json:"idx_tup_fetch,omitempty"`
	IdxBlksRead int64 `protobuf:"varint,7,opt,name=idx_blks_read,json=idxBlksRead" json:"idx_blks_read,omitempty"`
	IdxBlksHit  int64 `protobuf:"varint,8,opt,name=idx_blks_hit,json=idxBlksHit" json:"idx_blks_hit,omitempty"`
}

func (m *IndexStatistic) Reset()                    { *m = IndexStatistic{} }
func (m *IndexStatistic) String() string            { return proto.CompactTextString(m) }
func (*IndexStatistic) ProtoMessage()               {}
func (*IndexStatistic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type IndexBloatStatistic struct {
	IndexIdx    int32 `protobuf:"varint,1,opt,name=index_idx,json=indexIdx" json:"index_idx,omitempty"`
	WastedBytes int64 `protobuf:"varint,2,opt,name=wasted_bytes,json=wastedBytes" json:"wasted_bytes,omitempty"`
	SizeBytes   int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes" json:"size_bytes,omitempty"`
}

func (m *IndexBloatStatistic) Reset()                    { *m = IndexBloatStatistic{} }
func (m *IndexBloatStatistic) String() string            { return proto.CompactTextString(m) }
func (*IndexBloatStatistic) ProtoMessage()               {}
func (*IndexBloatStatistic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type FunctionInformation struct {
	FunctionIdx     int32    `protobuf:"varint,1,opt,name=function_idx,json=functionIdx" json:"function_idx,omitempty"`
	Language        string   `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	Source          string   `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	SourceBin       string   `protobuf:"bytes,5,opt,name=source_bin,json=sourceBin" json:"source_bin,omitempty"`
	Config          []string `protobuf:"bytes,6,rep,name=config" json:"config,omitempty"`
	Result          string   `protobuf:"bytes,8,opt,name=result" json:"result,omitempty"`
	Aggregate       bool     `protobuf:"varint,9,opt,name=aggregate" json:"aggregate,omitempty"`
	Window          bool     `protobuf:"varint,10,opt,name=window" json:"window,omitempty"`
	SecurityDefiner bool     `protobuf:"varint,11,opt,name=security_definer,json=securityDefiner" json:"security_definer,omitempty"`
	Leakproof       bool     `protobuf:"varint,12,opt,name=leakproof" json:"leakproof,omitempty"`
	Strict          bool     `protobuf:"varint,13,opt,name=strict" json:"strict,omitempty"`
	ReturnsSet      bool     `protobuf:"varint,14,opt,name=returns_set,json=returnsSet" json:"returns_set,omitempty"`
	Volatile        string   `protobuf:"bytes,15,opt,name=volatile" json:"volatile,omitempty"`
}

func (m *FunctionInformation) Reset()                    { *m = FunctionInformation{} }
func (m *FunctionInformation) String() string            { return proto.CompactTextString(m) }
func (*FunctionInformation) ProtoMessage()               {}
func (*FunctionInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

type FunctionStatistic struct {
	FunctionIdx int32   `protobuf:"varint,1,opt,name=function_idx,json=functionIdx" json:"function_idx,omitempty"`
	Calls       int64   `protobuf:"varint,2,opt,name=calls" json:"calls,omitempty"`
	TotalTime   float64 `protobuf:"fixed64,3,opt,name=total_time,json=totalTime" json:"total_time,omitempty"`
	SelfTime    float64 `protobuf:"fixed64,4,opt,name=self_time,json=selfTime" json:"self_time,omitempty"`
}

func (m *FunctionStatistic) Reset()                    { *m = FunctionStatistic{} }
func (m *FunctionStatistic) String() string            { return proto.CompactTextString(m) }
func (*FunctionStatistic) ProtoMessage()               {}
func (*FunctionStatistic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func init() {
	proto.RegisterType((*FullSnapshot)(nil), "pganalyze.collector.FullSnapshot")
	proto.RegisterType((*NullString)(nil), "pganalyze.collector.NullString")
	proto.RegisterType((*NullTimestamp)(nil), "pganalyze.collector.NullTimestamp")
	proto.RegisterType((*RoleReference)(nil), "pganalyze.collector.RoleReference")
	proto.RegisterType((*DatabaseReference)(nil), "pganalyze.collector.DatabaseReference")
	proto.RegisterType((*RoleInformation)(nil), "pganalyze.collector.RoleInformation")
	proto.RegisterType((*DatabaseInformation)(nil), "pganalyze.collector.DatabaseInformation")
	proto.RegisterType((*PostgresVersion)(nil), "pganalyze.collector.PostgresVersion")
	proto.RegisterType((*LogLine)(nil), "pganalyze.collector.LogLine")
	proto.RegisterType((*Setting)(nil), "pganalyze.collector.Setting")
	proto.RegisterType((*Backend)(nil), "pganalyze.collector.Backend")
	proto.RegisterType((*System)(nil), "pganalyze.collector.System")
	proto.RegisterType((*RelationReference)(nil), "pganalyze.collector.RelationReference")
	proto.RegisterType((*IndexReference)(nil), "pganalyze.collector.IndexReference")
	proto.RegisterType((*FunctionReference)(nil), "pganalyze.collector.FunctionReference")
	proto.RegisterType((*QueryReference)(nil), "pganalyze.collector.QueryReference")
	proto.RegisterType((*QueryInformation)(nil), "pganalyze.collector.QueryInformation")
	proto.RegisterType((*QueryStatistic)(nil), "pganalyze.collector.QueryStatistic")
	proto.RegisterType((*QueryExplain)(nil), "pganalyze.collector.QueryExplain")
	proto.RegisterType((*RelationInformation)(nil), "pganalyze.collector.RelationInformation")
	proto.RegisterType((*RelationInformation_Column)(nil), "pganalyze.collector.RelationInformation.Column")
	proto.RegisterType((*RelationInformation_Constraint)(nil), "pganalyze.collector.RelationInformation.Constraint")
	proto.RegisterType((*RelationStatistic)(nil), "pganalyze.collector.RelationStatistic")
	proto.RegisterType((*RelationEvent)(nil), "pganalyze.collector.RelationEvent")
	proto.RegisterType((*RelationBloatStatistic)(nil), "pganalyze.collector.RelationBloatStatistic")
	proto.RegisterType((*IndexInformation)(nil), "pganalyze.collector.IndexInformation")
	proto.RegisterType((*IndexStatistic)(nil), "pganalyze.collector.IndexStatistic")
	proto.RegisterType((*IndexBloatStatistic)(nil), "pganalyze.collector.IndexBloatStatistic")
	proto.RegisterType((*FunctionInformation)(nil), "pganalyze.collector.FunctionInformation")
	proto.RegisterType((*FunctionStatistic)(nil), "pganalyze.collector.FunctionStatistic")
	proto.RegisterEnum("pganalyze.collector.LogLine_SourceType", LogLine_SourceType_name, LogLine_SourceType_value)
	proto.RegisterEnum("pganalyze.collector.RelationEvent_EventType", RelationEvent_EventType_name, RelationEvent_EventType_value)
}

var fileDescriptor0 = []byte{
	// 3324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x39, 0xcd, 0x73, 0x23, 0x47,
	0xf5, 0x91, 0xe5, 0x0f, 0xa9, 0x25, 0x5b, 0x72, 0x7b, 0xbd, 0xab, 0xec, 0x2f, 0x3f, 0x92, 0x4c,
	0x3e, 0x21, 0xc1, 0x49, 0x6d, 0x20, 0x84, 0x0a, 0x81, 0x78, 0xd7, 0xbb, 0xc4, 0x85, 0x77, 0x37,
	0x19, 0xdb, 0x9b, 0x40, 0x15, 0x4c, 0x8d, 0xa5, 0x96, 0x3c, 0xec, 0x68, 0x66, 0x76, 0x7a, 0xb4,
	0xb6, 0xb7, 0xe0, 0xc0, 0x8d, 0x1b, 0x9c, 0xf9, 0x2b, 0x28, 0x0e, 0x39, 0x73, 0x0c, 0x70, 0x03,
	0x8a, 0x0b, 0x10, 0x3e, 0xcf, 0x5c, 0x72, 0xe0, 0xca, 0x7b, 0xaf, 0xbb, 0x67, 0x7a, 0x64, 0x59,
	0x52, 0x20, 0x17, 0x95, 0xfa, 0x7d, 0xf5, 0xeb, 0xf7, 0x5e, 0xbf, 0x8f, 0x1e, 0xb6, 0x26, 0x23,
	0x3f, 0x91, 0xc7, 0x71, 0xb6, 0x95, 0xa4, 0x71, 0x16, 0xf3, 0x8d, 0x64, 0xe0, 0x47, 0x7e, 0x78,
	0xf6, 0x48, 0x6c, 0x75, 0xe3, 0x30, 0x14, 0xdd, 0x2c, 0x4e, 0xaf, 0x3e, 0x39, 0x88, 0xe3, 0x41,
	0x28, 0x5e, 0x21, 0x92, 0xa3, 0x51, 0xff, 0x95, 0x2c, 0x18, 0x0a, 0x99, 0xf9, 0xc3, 0x44, 0x71,
	0x39, 0x3f, 0xe5, 0xac, 0x79, 0x6b, 0x14, 0x86, 0xfb, 0x5a, 0x18, 0xff, 0x12, 0xbb, 0x6c, 0x04,
	0x7b, 0x0f, 0x45, 0x2a, 0x83, 0x38, 0xf2, 0x86, 0xfe, 0xf7, 0xe3, 0xb4, 0x53, 0x79, 0xaa, 0xf2,
	0xe2, 0x92, 0x7b, 0xc9, 0x60, 0xef, 0x29, 0xe4, 0x6d, 0xc4, 0x4d, 0xe6, 0x0a, 0x22, 0xe0, 0x5a,
	0x98, 0xcc, 0x85, 0x38, 0xfe, 0x12, 0x5b, 0xcf, 0x55, 0x35, 0x6c, 0x9d, 0x2a, 0x30, 0xd4, 0xdd,
	0x76, 0x8e, 0xd0, 0x1c, 0xfc, 0x19, 0xb6, 0x9a, 0x6f, 0x31, 0x1a, 0x05, 0xbd, 0x0e, 0x23, 0xc2,
	0xa6, 0x01, 0x1e, 0x02, 0x8c, 0xbf, 0xc5, 0x9a, 0x9a, 0x51, 0xf4, 0x3c, 0x3f, 0xeb, 0x34, 0x80,
	0xa6, 0x71, 0xed, 0xea, 0x96, 0x32, 0xc3, 0x96, 0x31, 0xc3, 0xd6, 0x81, 0x31, 0x83, 0xdb, 0xc8,
	0xe9, 0xb7, 0x33, 0xfe, 0x3a, 0xbb, 0x52, 0xb0, 0x07, 0x51, 0x26, 0xd2, 0x87, 0x7e, 0xe8, 0x49,
	0xd1, 0x95, 0x9d, 0x26, 0x9d, 0x63, 0x33, 0x47, 0xef, 0x6a, 0xec, 0x3e, 0x20, 0xf9, 0x5d, 0xd6,
	0x4e, 0x62, 0x99, 0x0d, 0x52, 0x21, 0xf3, 0x73, 0x08, 0xda, 0xfa, 0xd9, 0xad, 0x09, 0x6e, 0xd9,
	0x7a, 0x57, 0x13, 0xeb, 0xb3, 0xb9, 0xad, 0xa4, 0x0c, 0xe0, 0xdf, 0x62, 0xad, 0x34, 0x0e, 0x85,
	0x97, 0x8a, 0xbe, 0x48, 0x45, 0xd4, 0x15, 0xb2, 0xd3, 0x7f, 0xaa, 0x0a, 0xf2, 0x9c, 0x89, 0xf2,
	0x5c, 0xa0, 0x75, 0x0d, 0xa9, 0xbb, 0x96, 0xda, 0x4b, 0xc9, 0xdf, 0x67, 0x1b, 0x3d, 0x3f, 0xf3,
	0x8f, 0x7c, 0x59, 0x12, 0x38, 0x20, 0x81, 0xcf, 0x4f, 0x14, 0xb8, 0xa3, 0xe9, 0x0b, 0xa1, 0xbc,
	0x37, 0x0e, 0x92, 0xfc, 0x3d, 0xb6, 0x4e, 0x5a, 0x06, 0x51, 0x3f, 0x4e, 0x87, 0x7e, 0x06, 0x9a,
	0xcb, 0x4e, 0x44, 0x62, 0x9f, 0xbd, 0x50, 0xcf, 0xdd, 0x82, 0xd8, 0x6d, 0xa7, 0x65, 0x80, 0xe4,
	0xdf, 0x65, 0x9b, 0xb9, 0xae, 0x25, 0xb1, 0x31, 0x89, 0x7d, 0x71, 0xaa, 0xb6, 0xb6, 0xe8, 0x4b,
	0xbd, 0xf3, 0x40, 0xc9, 0x5f, 0x65, 0x8b, 0x61, 0x3c, 0x90, 0x9d, 0x53, 0x92, 0xf6, 0xc4, 0x44,
	0x69, 0x7b, 0xf1, 0x60, 0x2f, 0x88, 0x84, 0x4b, 0x94, 0xfc, 0x0d, 0x56, 0x3b, 0xf2, 0xbb, 0xf7,
	0x45, 0xd4, 0x93, 0x9d, 0xb3, 0x29, 0x5c, 0xd7, 0x15, 0x91, 0x9b, 0x53, 0x23, 0xa7, 0x14, 0x59,
	0x16, 0x44, 0xb0, 0xdf, 0xa3, 0x29, 0x9c, 0xfb, 0x8a, 0xc8, 0xcd, 0xa9, 0x31, 0x9c, 0x1e, 0x8c,
	0x44, 0x7a, 0x66, 0x7b, 0xeb, 0xa3, 0x0a, 0x89, 0x78, 0x66, 0xa2, 0x88, 0xf7, 0x90, 0xba, 0xf0,
	0x55, 0xeb, 0x41, 0x69, 0x2d, 0xf9, 0x07, 0x6c, 0x23, 0x15, 0x21, 0xd9, 0xc0, 0x96, 0xf9, 0xab,
	0xca, 0x94, 0x10, 0x70, 0x35, 0x83, 0x15, 0x02, 0xe9, 0x38, 0x88, 0x54, 0x0d, 0xa2, 0x9e, 0x38,
	0xb5, 0xc5, 0xfe, 0x7a, 0x9a, 0xaa, 0xbb, 0x48, 0x6d, 0xa9, 0x1a, 0x94, 0xd6, 0xa4, 0x6a, 0x7f,
	0x14, 0x75, 0xc7, 0x55, 0xfd, 0xcd, 0x34, 0x55, 0x6f, 0x69, 0x06, 0x4b, 0xd5, 0xfe, 0x38, 0x48,
	0xf2, 0x43, 0xc6, 0x95, 0x55, 0x4b, 0x71, 0xf5, 0x5b, 0x25, 0xf8, 0xb9, 0x8b, 0xed, 0x6a, 0x47,
	0xd5, 0xfa, 0x83, 0x31, 0x88, 0xe5, 0x2c, 0xc8, 0x27, 0x59, 0x20, 0xb3, 0x00, 0x92, 0xc5, 0xef,
	0x66, 0x3a, 0x6b, 0xdf, 0x10, 0x6b, 0x67, 0xe5, 0x6b, 0xc9, 0x77, 0xd9, 0x9a, 0x12, 0x28, 0x4e,
	0x93, 0xd0, 0x0f, 0x40, 0xc7, 0xdf, 0x2b, 0x71, 0x4f, 0x5f, 0x2c, 0xee, 0xa6, 0x22, 0x75, 0x57,
	0x1f, 0x58, 0x2b, 0xc9, 0xbf, 0xc7, 0x36, 0x73, 0xbf, 0x97, 0x4e, 0xfd, 0xa7, 0xca, 0x94, 0xeb,
	0x64, 0x3c, 0x5f, 0xba, 0x4e, 0xe9, 0x79, 0x60, 0x39, 0xae, 0xac, 0xe3, 0xff, 0x79, 0x9e, 0xb8,
	0x2a, 0x2c, 0x90, 0xc7, 0x95, 0x65, 0x84, 0x63, 0xf6, 0x78, 0x2e, 0xf9, 0x28, 0x8c, 0xfd, 0xcc,
	0x96, 0xff, 0xb1, 0x92, 0xff, 0xd2, 0x54, 0xf9, 0xd7, 0x91, 0xab, 0xd8, 0xe4, 0x4a, 0x3a, 0x11,
	0x2e, 0xf9, 0x1e, 0xa4, 0x5a, 0xb3, 0x93, 0x78, 0x28, 0xa2, 0x4c, 0x76, 0xfe, 0x52, 0x99, 0x96,
	0x6b, 0x35, 0xf1, 0x4d, 0xa4, 0x85, 0x5c, 0x6b, 0x2f, 0x29, 0xc8, 0xd4, 0x7d, 0x28, 0x99, 0xfb,
	0xaf, 0xd3, 0x82, 0x8c, 0x6e, 0x44, 0x29, 0xc8, 0x82, 0x31, 0x88, 0x75, 0xcd, 0x2c, 0x2b, 0xfc,
	0x6d, 0xe6, 0x35, 0xb3, 0x82, 0x2c, 0x28, 0xad, 0x25, 0xf7, 0xd8, 0x65, 0x25, 0xf0, 0x9c, 0x71,
	0xff, 0x3e, 0x2d, 0x34, 0x48, 0xec, 0x98, 0x65, 0x2f, 0x05, 0xe7, 0x81, 0x14, 0x7a, 0xf9, 0x3d,
	0x2e, 0xd9, 0xe2, 0x1f, 0xd3, 0xe4, 0x9b, 0x9b, 0x5c, 0x0a, 0xbd, 0xfe, 0x79, 0x60, 0x39, 0x4f,
	0x58, 0xda, 0xff, 0x73, 0x9e, 0x3c, 0x61, 0x85, 0x5e, 0x7f, 0x1c, 0x24, 0x9d, 0x37, 0x18, 0xbb,
	0x83, 0x1d, 0x51, 0x96, 0x42, 0x32, 0xe6, 0x97, 0xd8, 0x12, 0x54, 0x79, 0x68, 0x37, 0xb0, 0xfd,
	0xa9, 0xb9, 0x6a, 0xa1, 0xa1, 0x23, 0x41, 0xed, 0x4d, 0xdd, 0x55, 0x0b, 0xe7, 0x7d, 0xb6, 0x8a,
	0x9c, 0x79, 0x73, 0x71, 0x01, 0xf3, 0xab, 0x36, 0xf3, 0xf4, 0xee, 0x44, 0x0b, 0x86, 0xde, 0xa7,
	0x54, 0xe2, 0x39, 0x67, 0x8b, 0x91, 0x3f, 0x14, 0x24, 0xb7, 0xee, 0xd2, 0x7f, 0xe7, 0x05, 0xb6,
	0x7e, 0xae, 0x6c, 0x4f, 0x24, 0xfc, 0x79, 0x95, 0xb5, 0xc6, 0x2a, 0x31, 0x7f, 0x9c, 0xd5, 0x54,
	0x29, 0xef, 0x9d, 0xea, 0x46, 0x6f, 0x85, 0x6a, 0x73, 0xef, 0x94, 0x77, 0xd8, 0x4a, 0x10, 0x1d,
	0x8b, 0x34, 0xc8, 0x48, 0xe1, 0x9a, 0x6b, 0x96, 0x78, 0x3c, 0xa8, 0x91, 0x81, 0xea, 0xd9, 0xe0,
	0x78, 0xb4, 0xe0, 0xff, 0xc7, 0xea, 0xdd, 0x54, 0xf8, 0x99, 0xf0, 0x7a, 0x47, 0x9d, 0x45, 0xc2,
	0xd4, 0x14, 0x60, 0xe7, 0x88, 0x3f, 0xc9, 0x1a, 0x1a, 0x89, 0xe2, 0x3b, 0x4b, 0x84, 0x66, 0x0a,
	0x84, 0x3a, 0xf1, 0xff, 0x67, 0x4c, 0x8e, 0x12, 0x91, 0x7a, 0x23, 0x29, 0xd2, 0xce, 0x32, 0xe1,
	0xeb, 0x04, 0x39, 0x04, 0x00, 0x7f, 0x8a, 0x35, 0x52, 0x91, 0x84, 0x41, 0x97, 0xd4, 0xee, 0xac,
	0x10, 0xde, 0x06, 0xa1, 0x80, 0xa3, 0xb3, 0xc4, 0x97, 0xd2, 0x4b, 0x43, 0xd9, 0xa9, 0x29, 0x01,
	0x0a, 0xe2, 0x86, 0x92, 0x7f, 0x9e, 0x41, 0x6b, 0x19, 0x45, 0x42, 0x45, 0x4e, 0x18, 0x0c, 0xe1,
	0x58, 0x75, 0x3a, 0x70, 0xab, 0x80, 0xef, 0x21, 0x98, 0x1f, 0xb0, 0x4b, 0xc8, 0x75, 0x12, 0xa7,
	0x3d, 0x8f, 0x3c, 0xe7, 0x8d, 0xa2, 0x2c, 0x08, 0xa9, 0xf1, 0xbc, 0x28, 0x3b, 0x94, 0xfc, 0xef,
	0x72, 0xc3, 0x7f, 0x0f, 0xd9, 0x0f, 0x91, 0x9b, 0x5f, 0x66, 0xcb, 0xb0, 0x51, 0x3f, 0x18, 0x40,
	0x73, 0x5a, 0x05, 0x9f, 0xe8, 0x15, 0x9a, 0x6d, 0x28, 0x86, 0x47, 0x70, 0xf2, 0xb8, 0x0f, 0xdd,
	0x66, 0x15, 0x34, 0xaa, 0x29, 0xc0, 0xdd, 0xbe, 0xf3, 0xef, 0x05, 0xb6, 0x31, 0xa1, 0xcb, 0xe1,
	0x4f, 0xb3, 0x66, 0xd1, 0x2e, 0xe5, 0xae, 0x6b, 0xe4, 0xbd, 0x0f, 0xb8, 0xef, 0x59, 0xb6, 0x16,
	0x9f, 0x44, 0x20, 0x36, 0xf7, 0xaf, 0x6a, 0xc9, 0x9b, 0x04, 0x75, 0xb5, 0x93, 0xaf, 0xb2, 0x1a,
	0xc4, 0x4b, 0xdc, 0x83, 0x90, 0xd7, 0x1d, 0x78, 0xbe, 0xc6, 0x00, 0xc0, 0x03, 0x82, 0x87, 0xc8,
	0x9d, 0x75, 0xd7, 0x2c, 0xf9, 0x26, 0x9c, 0xc5, 0xcb, 0xce, 0x12, 0xe5, 0x48, 0xb8, 0x07, 0xdd,
	0x03, 0x58, 0xa0, 0x93, 0x03, 0xe9, 0x65, 0x62, 0x98, 0x10, 0x93, 0x72, 0x22, 0x0b, 0xe4, 0x81,
	0x86, 0x60, 0xe3, 0xef, 0x87, 0x61, 0x7c, 0xe2, 0x15, 0x26, 0x97, 0xda, 0x97, 0x6d, 0x42, 0xdc,
	0x28, 0xe0, 0x13, 0x3d, 0x56, 0x9b, 0xec, 0x31, 0xf0, 0x7d, 0x3f, 0x8d, 0x1f, 0x89, 0xc8, 0x3b,
	0x85, 0x4b, 0x87, 0x6e, 0x5d, 0x75, 0xeb, 0x0a, 0xf2, 0x01, 0x5c, 0xbc, 0x6b, 0x6c, 0x13, 0x86,
	0x92, 0x60, 0x38, 0x1a, 0x7a, 0xc3, 0x51, 0x98, 0x05, 0xa7, 0x7e, 0x37, 0x23, 0x4a, 0x46, 0x94,
	0x1b, 0x1a, 0x79, 0xdb, 0xe0, 0x80, 0xc7, 0x39, 0x64, 0xad, 0xb1, 0x6e, 0x1d, 0xef, 0x54, 0x1f,
	0xdc, 0x6c, 0xee, 0x14, 0xfe, 0xc7, 0xab, 0x00, 0x43, 0x48, 0x9a, 0x99, 0x84, 0x40, 0x0b, 0xb4,
	0x5c, 0x34, 0x1a, 0xc2, 0x5d, 0xe9, 0x92, 0x51, 0xab, 0xae, 0x59, 0x3a, 0x3f, 0xaa, 0xb2, 0x15,
	0xdd, 0x68, 0xa2, 0xb9, 0xe2, 0x6e, 0x77, 0x94, 0xa6, 0x6a, 0x66, 0xa9, 0x10, 0x25, 0x33, 0x20,
	0x18, 0x4b, 0xbe, 0xc1, 0x96, 0x65, 0x3c, 0x4a, 0xbb, 0x2a, 0x63, 0xac, 0x5d, 0x7b, 0x61, 0x5a,
	0xdf, 0xba, 0xb5, 0x4f, 0xa4, 0xe8, 0x08, 0x57, 0xb3, 0xf1, 0xaf, 0xc1, 0x95, 0x0c, 0x03, 0x28,
	0x50, 0x5e, 0x90, 0x90, 0x26, 0x8d, 0x6b, 0x4f, 0x5e, 0x18, 0xbe, 0x2a, 0xf1, 0xc1, 0x9d, 0x25,
	0x8e, 0xdd, 0x04, 0x23, 0x13, 0x6e, 0xb6, 0x17, 0x42, 0x75, 0x0c, 0x75, 0x04, 0xd4, 0x00, 0xb0,
	0x87, 0x6b, 0x54, 0x5e, 0x77, 0xbc, 0x5e, 0x02, 0x96, 0x5c, 0x22, 0xc7, 0x30, 0x0d, 0x7a, 0x17,
	0x8c, 0x4e, 0xd1, 0x03, 0xc3, 0x52, 0x94, 0x51, 0x20, 0x50, 0xf4, 0xd0, 0x92, 0x7f, 0x93, 0xb5,
	0xfd, 0x5e, 0x2f, 0x40, 0xf7, 0xc1, 0x94, 0x15, 0x82, 0xee, 0x18, 0x04, 0xb3, 0x1b, 0xf3, 0x56,
	0xc1, 0x85, 0x6b, 0xe9, 0x7c, 0x99, 0xb1, 0xe2, 0xd0, 0xe0, 0x9e, 0x35, 0xe3, 0x31, 0x05, 0x6d,
	0x3f, 0xc6, 0x37, 0x58, 0x6b, 0x7b, 0xe8, 0x3f, 0x82, 0x6a, 0xd2, 0x33, 0xc0, 0x8a, 0xf3, 0x21,
	0xf8, 0x40, 0x37, 0xdf, 0x93, 0xf2, 0x24, 0x4e, 0x9c, 0xe4, 0x02, 0x30, 0x9b, 0x9d, 0xec, 0x9b,
	0x1a, 0x78, 0x0f, 0x61, 0xfc, 0x35, 0xb6, 0x38, 0x8a, 0x20, 0x22, 0xe7, 0xb4, 0x2a, 0x11, 0xf3,
	0xaf, 0x43, 0x8e, 0x8a, 0x63, 0x23, 0x76, 0x71, 0x3e, 0xd6, 0x3a, 0xb2, 0xa8, 0x4d, 0xdf, 0xc6,
	0x2c, 0x08, 0xe3, 0x82, 0x16, 0xb0, 0x34, 0x9f, 0x00, 0x46, 0x3c, 0x4a, 0xc2, 0x57, 0xf2, 0x90,
	0x5a, 0x9e, 0x8f, 0xd9, 0x84, 0x12, 0x6c, 0xad, 0xfe, 0x79, 0xfd, 0x00, 0x12, 0xf8, 0xca, 0x9c,
	0x5b, 0x2b, 0x9e, 0x5b, 0xc0, 0x62, 0x49, 0x40, 0x97, 0xd3, 0x55, 0x9e, 0x5f, 0x02, 0x3a, 0xdc,
	0xf9, 0x03, 0x38, 0x4e, 0xcf, 0x5b, 0xbc, 0xcd, 0xaa, 0x89, 0x2e, 0xb0, 0x55, 0x17, 0xff, 0x62,
	0x2a, 0xc3, 0xda, 0x41, 0xee, 0x54, 0x1e, 0xcb, 0xd7, 0x98, 0x4b, 0xfc, 0x24, 0xaf, 0x15, 0x1e,
	0xd1, 0xa8, 0x74, 0xd7, 0xb2, 0xe0, 0x77, 0x90, 0x14, 0x2b, 0x95, 0xba, 0x33, 0x10, 0x6e, 0xa9,
	0x8e, 0x7b, 0xa6, 0x40, 0xdb, 0x00, 0x81, 0x5b, 0xb9, 0x6a, 0x22, 0x1f, 0xb2, 0x3d, 0x5c, 0xfd,
	0xa5, 0x99, 0xe5, 0xbc, 0xa9, 0x19, 0xf6, 0x91, 0x9e, 0x7f, 0x95, 0x31, 0xca, 0x40, 0x8a, 0x7b,
	0x79, 0x26, 0x77, 0x1d, 0xa9, 0x15, 0xeb, 0x9b, 0xac, 0x91, 0x0f, 0x1d, 0xc0, 0xbb, 0x32, 0x93,
	0x97, 0x99, 0x29, 0x03, 0x98, 0xdf, 0x62, 0x4d, 0xec, 0x98, 0x84, 0xd7, 0x3d, 0xf6, 0xa3, 0x81,
	0xf1, 0xc0, 0xd4, 0x47, 0x12, 0xa2, 0xbf, 0x41, 0xe4, 0x78, 0xa1, 0x4f, 0xfc, 0x00, 0x6f, 0x0d,
	0x65, 0x58, 0xe8, 0x07, 0xf4, 0x92, 0x92, 0x20, 0x12, 0xea, 0xa7, 0x19, 0xb5, 0x40, 0x9b, 0x47,
	0x58, 0xb0, 0xc2, 0xe0, 0x11, 0x24, 0x38, 0xd2, 0x83, 0xde, 0x65, 0xc0, 0xe6, 0x05, 0x9c, 0xa6,
	0x18, 0xa7, 0xc6, 0x96, 0xf7, 0xcf, 0x24, 0x14, 0x0e, 0xe7, 0x07, 0x6c, 0xfd, 0xdc, 0x00, 0x3a,
	0x4f, 0xb5, 0x03, 0xaf, 0xc9, 0xee, 0xb1, 0x18, 0xfa, 0x9e, 0xe5, 0x7f, 0xa6, 0x40, 0x77, 0xf4,
	0xa5, 0xce, 0xdb, 0x7d, 0xcb, 0xfd, 0x4d, 0x03, 0x44, 0x22, 0x47, 0xb2, 0xb5, 0xf2, 0x9c, 0xfa,
	0x99, 0x6c, 0x0d, 0xd5, 0x49, 0xf5, 0xdc, 0xd6, 0xbe, 0x75, 0x82, 0xd0, 0xa6, 0x3f, 0xab, 0xb0,
	0xf5, 0x73, 0x93, 0xec, 0x67, 0x75, 0xe6, 0xbc, 0x57, 0xb6, 0xcf, 0x6c, 0x80, 0x44, 0xf4, 0x04,
	0xab, 0xfb, 0xe9, 0x00, 0xca, 0x13, 0x4e, 0x40, 0x2a, 0xda, 0x0b, 0x80, 0x93, 0xb0, 0xb5, 0xf2,
	0x23, 0xc3, 0x3c, 0x8a, 0xd9, 0x4d, 0xe5, 0x42, 0xb9, 0xa9, 0x84, 0x3e, 0xae, 0x0f, 0x21, 0x23,
	0xd2, 0x04, 0x6e, 0xb7, 0xca, 0x9e, 0x4d, 0xd7, 0x06, 0x39, 0x27, 0xac, 0x3d, 0x3e, 0x7e, 0x63,
	0x25, 0xd2, 0x23, 0x7c, 0xbe, 0x61, 0x4d, 0x4d, 0xe4, 0x20, 0x72, 0x52, 0x9c, 0x2d, 0x4c, 0x8c,
	0x33, 0x5b, 0x8e, 0x84, 0xbd, 0xab, 0x90, 0x3a, 0x8c, 0x1c, 0xe9, 0xfc, 0x6b, 0x51, 0x9f, 0x35,
	0x9f, 0x09, 0xa6, 0xef, 0x0b, 0x51, 0xdf, 0x85, 0xa6, 0x45, 0xd2, 0x66, 0x55, 0x57, 0x2d, 0xd0,
	0xd9, 0x59, 0x9c, 0x41, 0x5d, 0xc3, 0x17, 0x57, 0x3a, 0x5f, 0xc5, 0xad, 0x13, 0x04, 0xaf, 0x15,
	0xd6, 0x9b, 0x34, 0x3e, 0x51, 0x86, 0xae, 0xba, 0xf4, 0x9f, 0x3f, 0xcf, 0x5a, 0xf2, 0xd8, 0xc7,
	0x2e, 0xe0, 0x28, 0xbc, 0x2f, 0xbd, 0xe3, 0x40, 0xa5, 0x94, 0xaa, 0xbb, 0xaa, 0xc0, 0xd7, 0x01,
	0xfa, 0x0e, 0x54, 0x8f, 0x17, 0x59, 0xdb, 0xa6, 0x83, 0xde, 0xb9, 0x47, 0xd9, 0xa3, 0xea, 0xae,
	0x15, 0x84, 0x2e, 0x40, 0xf9, 0x16, 0xdb, 0xb0, 0x29, 0x7b, 0x41, 0x9a, 0x05, 0xa2, 0x47, 0xe9,
	0xa2, 0xea, 0xae, 0x17, 0xc4, 0x3b, 0x0a, 0x31, 0x4e, 0x7f, 0x02, 0x4d, 0x3e, 0x54, 0x6a, 0x4a,
	0x10, 0x25, 0xfa, 0xf7, 0x15, 0x02, 0x7b, 0xcb, 0x30, 0x86, 0xf3, 0x16, 0x0a, 0xd7, 0x89, 0xb4,
	0x49, 0x50, 0xa3, 0x2f, 0x9c, 0xcb, 0xa2, 0x22, 0x75, 0x99, 0x3a, 0x57, 0x4e, 0x46, 0xda, 0xbe,
	0xcc, 0xb8, 0x45, 0x67, 0x94, 0x6d, 0x10, 0x69, 0x3b, 0x27, 0x35, 0xba, 0x96, 0xa9, 0x8d, 0xaa,
	0xcd, 0x31, 0x6a, 0x4b, 0x53, 0xec, 0x47, 0x2d, 0x15, 0x56, 0x95, 0xa6, 0x08, 0xcd, 0x35, 0xf8,
	0x02, 0x5b, 0x2f, 0xa8, 0x8c, 0xc8, 0x35, 0x22, 0x6c, 0x19, 0x42, 0x23, 0xd1, 0x81, 0xf4, 0x1f,
	0xde, 0x27, 0x59, 0xca, 0xc7, 0x2d, 0xf2, 0x71, 0x03, 0x80, 0x28, 0x8b, 0xbc, 0x0c, 0xbb, 0x22,
	0x0d, 0x4a, 0x12, 0x8a, 0xa8, 0x4d, 0x44, 0x4d, 0x80, 0xa2, 0x1c, 0x81, 0x54, 0xce, 0x2f, 0x2a,
	0xac, 0x69, 0xbf, 0xe2, 0x4c, 0x0f, 0xb7, 0xb1, 0x6e, 0x71, 0xf1, 0x5c, 0xb7, 0x08, 0xf9, 0x39,
	0xc5, 0x41, 0x65, 0xa8, 0x1a, 0x83, 0x8a, 0x6b, 0x96, 0xfc, 0x39, 0xb6, 0xa6, 0xdf, 0x94, 0xbc,
	0x78, 0x94, 0x25, 0x23, 0xd3, 0x91, 0xad, 0x6a, 0xe8, 0x5d, 0x02, 0x62, 0xba, 0x30, 0x64, 0x22,
	0x4d, 0xe3, 0x94, 0xe2, 0x05, 0xd2, 0x85, 0x06, 0xde, 0x44, 0x98, 0xf3, 0x49, 0x8d, 0x6d, 0x4c,
	0x78, 0x28, 0xc2, 0xb4, 0x50, 0x3c, 0x39, 0x15, 0x69, 0x21, 0x7f, 0x3e, 0x82, 0x13, 0xd8, 0x29,
	0x98, 0x86, 0x87, 0x85, 0x72, 0x0a, 0xa6, 0x2e, 0xee, 0x1d, 0xd6, 0x7a, 0x18, 0x88, 0x13, 0xaf,
	0x27, 0x20, 0x29, 0x50, 0xb7, 0x37, 0x6f, 0x8b, 0xb5, 0x86, 0x7c, 0x3b, 0x39, 0x1b, 0xdf, 0xa5,
	0xf1, 0x65, 0x34, 0x8c, 0xf0, 0xb6, 0x61, 0x77, 0xf9, 0xca, 0xbc, 0xaf, 0x5e, 0x5b, 0x37, 0x88,
	0xcf, 0x35, 0xfc, 0xfc, 0x10, 0x7a, 0x02, 0x18, 0x49, 0xb2, 0x14, 0xcc, 0x00, 0x59, 0x72, 0x89,
	0xc4, 0xbd, 0xf6, 0x29, 0xc4, 0x19, 0x5e, 0xd7, 0x96, 0x83, 0x99, 0x2b, 0xc1, 0xd9, 0x02, 0x2a,
	0x1f, 0x64, 0x56, 0x65, 0x13, 0xe5, 0x99, 0x96, 0x05, 0x27, 0xb3, 0x7c, 0x0e, 0x26, 0x9c, 0x20,
	0x0c, 0xfb, 0x3e, 0x6e, 0x42, 0x8e, 0x81, 0x6e, 0xbb, 0x80, 0x60, 0xca, 0x3d, 0xf6, 0xa5, 0x17,
	0x63, 0x62, 0x53, 0xb3, 0xef, 0x0a, 0xac, 0xef, 0x06, 0xf4, 0x1e, 0xdd, 0x41, 0x94, 0x1e, 0xde,
	0x7d, 0xdc, 0xa9, 0x7b, 0x1c, 0x84, 0x3d, 0x48, 0xe7, 0xba, 0x90, 0x5f, 0x06, 0xfc, 0x6e, 0x81,
	0xbe, 0xa1, 0xb1, 0x18, 0x8f, 0xc8, 0x99, 0xc5, 0xbe, 0xcc, 0xe8, 0xea, 0xc2, 0x44, 0x0f, 0x80,
	0x03, 0x5c, 0x8f, 0xcd, 0x5c, 0x8d, 0xb9, 0x67, 0xae, 0xe6, 0x85, 0x33, 0xd7, 0xd5, 0x0f, 0x2b,
	0x6c, 0x59, 0x99, 0x3e, 0xef, 0xcb, 0x17, 0xac, 0xbe, 0x1c, 0xd4, 0xc1, 0x2a, 0xa3, 0xec, 0xa4,
	0x87, 0x55, 0x04, 0x90, 0x81, 0x76, 0xd8, 0x2a, 0x84, 0x8c, 0x0f, 0xe2, 0x3e, 0x5d, 0x77, 0xdd,
	0xd4, 0x5c, 0xaa, 0x3d, 0x06, 0x33, 0x46, 0xd0, 0x9f, 0x47, 0x38, 0xe6, 0xa9, 0x37, 0x8a, 0x15,
	0x58, 0x23, 0x39, 0xb6, 0x97, 0x49, 0x2c, 0x55, 0x44, 0x2e, 0xab, 0xbb, 0x69, 0xd6, 0x57, 0x3f,
	0x5e, 0x60, 0xac, 0x70, 0x32, 0x7f, 0x95, 0x5d, 0x02, 0xe7, 0x8b, 0x60, 0x80, 0x4f, 0xd9, 0xe7,
	0xee, 0x04, 0xd7, 0x38, 0xd7, 0xba, 0x1a, 0x93, 0x8e, 0x0b, 0x30, 0xeb, 0xa4, 0xf4, 0x1f, 0x6f,
	0x72, 0x11, 0x40, 0x78, 0x47, 0x74, 0xc5, 0x5e, 0x2d, 0xa0, 0x70, 0x03, 0xf4, 0xe4, 0x4e, 0xa1,
	0xbf, 0x44, 0x2f, 0x0a, 0x79, 0x24, 0xbf, 0xc0, 0x5a, 0x46, 0x35, 0x43, 0xb1, 0x4c, 0x14, 0x6b,
	0x1a, 0x7c, 0x43, 0x13, 0x42, 0x49, 0x30, 0x84, 0xa3, 0xa4, 0x87, 0x5d, 0x23, 0x29, 0xa3, 0x52,
	0xc2, 0xba, 0x46, 0x1d, 0x12, 0x86, 0xec, 0x6f, 0xd1, 0xf7, 0x44, 0x28, 0x0c, 0x7d, 0xad, 0x44,
	0xbf, 0x43, 0x18, 0xa2, 0x87, 0x34, 0x6e, 0xe8, 0xe1, 0x96, 0x74, 0x8f, 0x15, 0x79, 0x5d, 0x7d,
	0x04, 0xd4, 0x98, 0xdb, 0x88, 0x40, 0x6a, 0xe7, 0x8f, 0x4b, 0x45, 0x5f, 0x58, 0x94, 0xe7, 0x39,
	0x72, 0x0e, 0x3e, 0x2b, 0x41, 0xfd, 0xf7, 0x8e, 0xce, 0x32, 0x61, 0x2a, 0x75, 0x1d, 0x21, 0xd7,
	0x11, 0x80, 0xfe, 0x96, 0xe2, 0x81, 0x27, 0xbb, 0x7e, 0x64, 0x26, 0x75, 0x58, 0xef, 0xc3, 0x12,
	0x3a, 0x95, 0x26, 0xa2, 0xb2, 0x51, 0xa2, 0xea, 0x86, 0x4e, 0xb8, 0x00, 0x3b, 0x18, 0x25, 0x54,
	0x35, 0x80, 0x19, 0x76, 0x55, 0xcc, 0xaa, 0x60, 0xaf, 0xc0, 0x9a, 0x98, 0xa1, 0x48, 0x20, 0x0a,
	0x99, 0xfb, 0x02, 0x0e, 0xa1, 0xeb, 0x74, 0x03, 0x80, 0xc0, 0x7d, 0x0b, 0x41, 0x10, 0x50, 0xf5,
	0x88, 0x28, 0x02, 0xfd, 0x08, 0x82, 0xcf, 0x04, 0x80, 0xdd, 0x05, 0xeb, 0xe7, 0x38, 0xb0, 0xbd,
	0x2e, 0xc3, 0x84, 0x03, 0x83, 0x17, 0x38, 0xb0, 0xb3, 0xae, 0xbb, 0x84, 0x03, 0xe3, 0x82, 0x45,
	0x56, 0x15, 0x8e, 0xbe, 0x96, 0x26, 0xa6, 0xe0, 0x32, 0xc4, 0xbf, 0x13, 0x67, 0xc8, 0xfe, 0x04,
	0x63, 0xf8, 0x9a, 0xf2, 0x50, 0x20, 0x9d, 0xae, 0xb2, 0xb5, 0x68, 0x0f, 0x00, 0x40, 0xa3, 0xb0,
	0x3d, 0xaa, 0x6d, 0x80, 0x6d, 0x6a, 0xec, 0x0e, 0x16, 0x36, 0xc0, 0x7e, 0x91, 0x6d, 0x80, 0xbb,
	0x62, 0x18, 0x7c, 0x02, 0x4c, 0x23, 0xfa, 0x62, 0xe9, 0x92, 0xda, 0x8e, 0x6e, 0xc7, 0xbd, 0x7d,
	0x44, 0x6c, 0x2b, 0x38, 0x96, 0xc1, 0x63, 0xe1, 0xdb, 0xc5, 0x97, 0xab, 0xe2, 0x8b, 0xd0, 0xbc,
	0xf8, 0x82, 0xad, 0x0a, 0x2a, 0xec, 0x25, 0x36, 0x94, 0xad, 0x0c, 0x11, 0xb6, 0x12, 0xda, 0x9e,
	0x85, 0xa0, 0x4b, 0xb9, 0x3d, 0x73, 0x39, 0xe0, 0xb0, 0x9c, 0x06, 0xc5, 0x6c, 0xaa, 0xa3, 0x6b,
	0x12, 0xdd, 0x90, 0x50, 0x2e, 0xb3, 0xe4, 0x5c, 0x56, 0x0d, 0x09, 0x81, 0x73, 0x49, 0xd8, 0x34,
	0x14, 0x74, 0x28, 0xeb, 0x8a, 0x6e, 0x1a, 0x0c, 0x19, 0x4a, 0x43, 0xaa, 0xb2, 0x52, 0x1d, 0x4d,
	0x65, 0x6b, 0x05, 0x9a, 0x67, 0x25, 0xb5, 0x1e, 0x57, 0x9a, 0x67, 0x85, 0x5e, 0xce, 0x2f, 0x17,
	0xd8, 0x6a, 0xe9, 0xf3, 0xc2, 0x3c, 0x91, 0xfd, 0xb6, 0x4e, 0x0f, 0xea, 0x69, 0xe8, 0xe5, 0xd9,
	0xdf, 0x2c, 0xb6, 0xe8, 0x97, 0xde, 0x87, 0x54, 0x32, 0x79, 0xb3, 0xdc, 0x51, 0x54, 0x67, 0x0f,
	0x93, 0x56, 0xb7, 0xf1, 0x3a, 0xbb, 0x02, 0x93, 0x73, 0x1a, 0x9f, 0x06, 0x43, 0x4c, 0x0e, 0xe3,
	0xad, 0x49, 0xcd, 0xdd, 0xb4, 0xd0, 0x77, 0x73, 0x3e, 0xe7, 0x90, 0xd5, 0x73, 0x3d, 0xf8, 0x3a,
	0x5b, 0xbd, 0xbd, 0x7d, 0xe7, 0x70, 0x7b, 0xcf, 0xbb, 0xb7, 0x7d, 0xe3, 0xf0, 0xf0, 0x76, 0xfb,
	0x31, 0xde, 0x62, 0x8d, 0xed, 0xc3, 0x83, 0xbb, 0x06, 0x50, 0xc1, 0x67, 0x1d, 0x4d, 0xb3, 0x7d,
	0x67, 0x7b, 0xef, 0xdb, 0xdf, 0xb9, 0xd9, 0x5e, 0x80, 0xe1, 0xbf, 0x49, 0x44, 0x06, 0x52, 0x75,
	0x7e, 0xc8, 0x2e, 0x4f, 0xfe, 0x00, 0x34, 0x8f, 0x29, 0x81, 0xe4, 0x04, 0x1c, 0x8b, 0xed, 0xaf,
	0x95, 0x26, 0x1a, 0x0a, 0xa6, 0x12, 0x45, 0x39, 0x8f, 0x54, 0xc7, 0xf2, 0x88, 0xf3, 0xd1, 0x02,
	0x6b, 0x8f, 0x7f, 0xcf, 0xc1, 0x7a, 0xa5, 0xbf, 0x09, 0x15, 0xed, 0x9c, 0xfa, 0xc4, 0xa3, 0xf6,
	0x2c, 0xa9, 0xb5, 0x70, 0x5e, 0x2d, 0x2b, 0x8b, 0x57, 0xcb, 0x59, 0x3c, 0x97, 0x5c, 0x54, 0x00,
	0x25, 0x19, 0x93, 0xff, 0xad, 0x73, 0x35, 0x62, 0xce, 0x77, 0xa2, 0xb1, 0x22, 0x82, 0x63, 0xab,
	0xf4, 0x60, 0x28, 0x1b, 0xfa, 0x30, 0x51, 0xe9, 0x17, 0xf9, 0x40, 0xbe, 0xab, 0x00, 0xa4, 0x83,
	0xf4, 0x46, 0x51, 0x00, 0x1d, 0xaa, 0x7e, 0xc3, 0xad, 0x05, 0xf2, 0x90, 0xd6, 0x94, 0x1a, 0xa5,
	0x7a, 0x3c, 0x37, 0xed, 0x48, 0x20, 0xe9, 0x31, 0x7c, 0xac, 0x93, 0xa9, 0x8f, 0x77, 0x32, 0xce,
	0x27, 0x15, 0x3d, 0x84, 0x97, 0xc6, 0xb0, 0x8b, 0x0d, 0x39, 0x3b, 0xc3, 0xe7, 0x49, 0xba, 0x5a,
	0x4e, 0xd2, 0x3a, 0x61, 0x8c, 0x67, 0x78, 0x95, 0xa3, 0xcd, 0xe5, 0x9d, 0x99, 0xc6, 0xcf, 0xa5,
	0xa6, 0x95, 0xd9, 0xa9, 0xa9, 0x36, 0x9e, 0x9a, 0x9c, 0x8c, 0x6d, 0x4c, 0xf8, 0xc6, 0x36, 0x33,
	0x84, 0xfe, 0xc7, 0xb0, 0xfd, 0x49, 0x95, 0x6d, 0x4c, 0xf8, 0xf4, 0x86, 0x92, 0x8b, 0x8f, 0x78,
	0xc5, 0x9d, 0xc9, 0x3f, 0xc8, 0xa9, 0x0f, 0x07, 0xa1, 0x1f, 0x0d, 0x46, 0xfe, 0x20, 0xef, 0xc5,
	0xcc, 0x1a, 0x3f, 0x75, 0xe8, 0x47, 0x46, 0x15, 0x9b, 0xe6, 0x0d, 0x11, 0xb5, 0x51, 0x2f, 0x80,
	0x47, 0x41, 0xa4, 0x3f, 0x1d, 0xd4, 0x15, 0xe4, 0x3a, 0x8c, 0x3f, 0xc5, 0x17, 0x92, 0xe5, 0xd2,
	0x17, 0x12, 0x80, 0xa7, 0x42, 0x42, 0x8f, 0xa6, 0xbb, 0x09, 0xbd, 0xa2, 0x97, 0x8b, 0xc1, 0x20,
	0x15, 0x03, 0x7c, 0x7a, 0x52, 0x9d, 0x6c, 0x01, 0x40, 0xae, 0x13, 0x30, 0x55, 0x7c, 0xa2, 0x3b,
	0x57, 0xbd, 0xc2, 0xa6, 0x5b, 0x0a, 0x48, 0x47, 0x41, 0x76, 0xa6, 0x86, 0x0c, 0x91, 0x52, 0x15,
	0xac, 0xb9, 0x2d, 0x03, 0xdf, 0x51, 0x60, 0xdc, 0x20, 0x14, 0xfe, 0x7d, 0x48, 0x63, 0xf4, 0x69,
	0x86, 0x36, 0xc8, 0x01, 0x74, 0x4a, 0xb8, 0x38, 0xdd, 0x8c, 0xea, 0x1f, 0x6c, 0xa0, 0x56, 0x38,
	0xa8, 0xa5, 0x22, 0x1b, 0xa5, 0x91, 0xf4, 0xa4, 0xc8, 0x68, 0x8c, 0xac, 0xe1, 0x1b, 0x2c, 0x81,
	0xf6, 0x45, 0x86, 0xa6, 0x7b, 0x18, 0xe3, 0x35, 0x0f, 0xd5, 0xf0, 0x08, 0xa6, 0x33, 0x6b, 0xe7,
	0xc7, 0xd6, 0x63, 0x50, 0x29, 0x87, 0xcd, 0xf2, 0xc7, 0x7f, 0xf5, 0x1a, 0x01, 0xe1, 0x25, 0x45,
	0xd8, 0x57, 0xd8, 0x45, 0xc2, 0xd6, 0x10, 0x80, 0xc8, 0xa3, 0x65, 0xaa, 0x00, 0xaf, 0xfd, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x3c, 0x55, 0x0c, 0x00, 0x71, 0x26, 0x00, 0x00,
}
